version: '3.7'

services:
  mongo:
    image: mongo:4.2.5
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  frontend-app:
    build: .
    ports:
      - 3000:3000
  backend-app:
    build: ./server
    environment:
        WAIT_HOSTS: mongo:27017
    ports:
      - 5000:5000