version: '1.0'

services:
  mongo:
    image: mongo:4.2.5
  frontend-app:
    build: .
    ports:
      - 3000:3000
  backend-app:
    build: ./server
    environment:
        WAIT_HOSTS: mongo:27017
    ports:
      - 5000:5000